### PR TITLE
fix aapt package name

### PR DESCRIPTION
**Pull request by ov3rk1ll**
Apparently the package name can (and does) also contain numbers

### CODE REVIEW

**Review by whitewhidow — CHANGES_REQUESTED** [review]
THX, Can you quickly add the underscore aswell


Since appearantly the specs say :
```
A full Java-language-style package name for the application. The name should be unique. The name may contain uppercase or lowercase letters ('A' through 'Z'), numbers, and underscores ('_'). However, individual package name parts may only start with letters.
```

OR IDEALLY, get that node-aapt package to properly use the builtin aapt from node-aapt, so we can get rid of that entire IF statement..

**Comment by ov3rk1ll** [comment]
I have updated the regex to match anything between the two `'`

**Comment by whitewhidow** [comment]
> I have updated the regex to match anything between the two `'`
> 
> // Edit: do think there could be an issue with using the actual code from https://github.com/vldmkr/node-aapt/blob/master/index.js#L26 for this?

that package does not support windows,   i am using a fork that should support windows : 

> I have updated the regex to match anything between the two `'`
> 
> // Edit: do think there could be an issue with using the actual code from https://github.com/vldmkr/node-aapt/blob/master/index.js#L26 for this?

their original package does not include a windows binary for aapt, i am using this fork : `https://github.com/whitewhidow/node-aapt/blob/master/index.js`

to which i added the windows binary, i did prolly indeed not need to replace the regexes there, as you mention could have prolly reused the existing part that parses stdout, however.

The problem i have on windows is,   that for some reason, i could not get it to properly run the exec on the aapt.exe for everyone.  (some ppl where getting "could not read package data" during the sideload process, because the `aapt dump badging` command failed, even tho it seemed to work fine for me actually)

feel free to play around with it, would be alot better to have it working with the builtin one

**Comment by ov3rk1ll** [comment]
I have update the regex again to match the parsing done in `node-aapt`.
This worked for me for my tests so I'd say that the goal of this MR is archived.

I'll take a look at the aapt command. Maybe this has something to do with the rclone mount file read on Window?!
There are pure JS parsers for APK files (e.g. https://www.npmjs.com/package/node-apk-parser) so maybe that would be a better option here?

**Review by whitewhidow — APPROVED** [review]

**Comment by whitewhidow** [comment]
> Maybe this has something to do with the rclone mount file read on Window?!

im not following ?  it is not mount related (it also fails on local files)
but the JS implementation of AAPT is definitely the way to go !!!   i did not know this was around !
(ill close this ticket, as the regex is fixed, maybe open a new one for the js implementation)

**Comment by ov3rk1ll** [comment]
> im not following ? it is not mount related (it also fails on local files)
Maybe I misunderstood the issue with aapt in that case.

> but the JS implementation of AAPT is definitely the way to go !!! i did not know this was around !
I'll take a look at the `node-apk-parser` package but I can only test this on Windows right now

**Comment by whitewhidow** [comment]
> > im not following ? it is not mount related (it also fails on local files)
> 
> Maybe I misunderstood the issue with aapt in that case.
> 
> > but the JS implementation of AAPT is definitely the way to go !!! i did not know this was around !
> 
> I'll take a look at the `node-apk-parser` package but I can only test this on Windows right now

ps i just lookad at the repo,  it does not seem to be a pure js implementation, seems to also use the actual existing aapt executable

**Comment by whitewhidow** [comment]
the best thing would be to just get the current implementation node-aapt working on windows, but for that i should figure out WHY it is not working ..
(if i remember correctly, it WAS working when running via npm, but was NOT working when running via compiled exe)

**Comment by whitewhidow** [comment]
@ov3rk1ll 
https://github.com/whitewhidow/quest-sidenoder/pull/22/commits/b929047b5a427fc8898d3848c7354e40a721df5f
seems like a pure js one indeed (very old tho, im sure it is not bugfree, but seems to work for most cases so far)

**Pull request merged**
